name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version:
          - 1.15
          - 1.16
          - 1.17

    runs-on: ${{ matrix.os }}
    
    steps:
    
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{go-version}}

    - name: Test
      run: go test -v
